version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mongodb
      - redis
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chat_app
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=chat_content
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chat_app
    ports:
      - "5433:5432"

  mongodb:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"

  redis:
    image: redis:7
    ports:
      - "6378:6379"

volumes:
  postgres_data:
  mongodb_data: 